apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: DOCKER_HUB_USER/projeto-database:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: DOCKER_HUB_USER/projeto-backend-php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
